title: PVP
description: "Personal Vault Project: An insightful, secure and searchable vault for your private data."
theme: just-the-docs

url: https://dlucian.github.io/pvp

aux_links:
  Docs Repository: https://github.com/dlucian/pvp

callouts:
  highlight:
    color: yellow
