version: "3.9"

services:

  roadrunner:
    container_name: roadrunner
    build:
      context: ./roadrunner
    restart: unless-stopped
    environment:
      - VAULT_PATH=${VAULT_PATH}
    networks:
      - internal
    volumes:
      - type: bind
        source: ${HOST_VAULT_PATH}
        target: ${VAULT_PATH}
      - ./roadrunner:/var/www
      - ./roadrunner/config:/etc/roadrunner
    depends_on:
      - database
    ports:
      - '7020:6001'
      - '7030:8080'

  # index:
  #   container_name: index
  #   build:
  #     context: ./index
  #   environment:
  #     - VAULT_PATH=${VAULT_PATH}
  #   volumes:
  #     - type: bind
  #       source: ${HOST_VAULT_PATH}
  #       target: ${VAULT_PATH}
  #   networks:
  #     - internal
  #   depends_on:
  #     - database
  #     - storage_init

  # llm:
  #   build:
  #     context: ./llm
  #   depends_on:
  #     - database

  database:
    container_name: postgres
    image: postgres:15-alpine3.18
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - internal
    restart: unless-stopped

  # viewer:
  #   build:
  #     context: ./viewer
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - database

networks:
  internal:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  storage_data:
