# Sample configuration:
# https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml

version: '3'
rpc:
    listen: 'tcp://:6001'
server:
    command: 'php /var/www/src/psr-worker.php'
    relay: pipes
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: /var/www/public
        forbid:
            - .php
            - .htaccess
    pool:
        debug: true
        num_workers: 4
        supervisor:
            max_worker_memory: 100
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
kv:
    local:
        driver: memory
        config:
            interval: 60
metrics:
    address: '127.0.0.1:2112'

# Logging settings (docs: https://roadrunner.dev/docs/plugins-logger/2.x/en)
logs:
  # Logging mode can be "development", "production" or "raw". Do not forget to change this value for production environment.
  #
  # Development mode (which makes DPanicLevel logs panic), uses a console encoder, writes to standard error, and
  # disables sampling. Stacktraces are automatically included on logs of WarnLevel and above.
  #
  # Default: "development"
  mode: development

  # Logging level can be "panic", "error", "warn", "info", "debug".
  #
  # Default: "debug"
  level: debug
